dataset_name: data-name.csv
generation_prompt: #prompt
gpu_config:
  hourly_cost: #in dollar
training_config:
  model_name: EQUES/MedLLama3-JP-v2
  max_length: 8192
  max_completion_length: 2048 
  peft_config:
    lora_alpha: 64 
    lora_dropout: 0.1
    lora_r: 128
  dpo_config:
    per_device_train_batch_size: 1
    per_device_eval_batch_size:  1 
    gradient_accumulation_steps: 2
    num_train_epochs: 1 
    max_grad_norm: 0.3 
save_config:
  new_model: 
  hf_token:
