dataset_name: dpo_data.csv
gpu_config:
  hourly_cost: 5.09
training_config:
  model_name: EQUES/MedLLama3-JP-v2
  max_length: 8192
  max_completion_length: 2048 
  peft_config:
    lora_alpha: 64 #自分によって変えることできます
    lora_dropout: 0.1 #自分によって変えることできます
    lora_r: 128 #自分によって変えることできます
  dpo_config:
    per_device_train_batch_size: 1
    per_device_eval_batch_size:  1 
    gradient_accumulation_steps: 2
    num_train_epochs: 1 #自分によって変えることできます.(1から3までの範囲)
    max_grad_norm: 0.3 #自分によって変えることできます
save_config:
  new_model: 
  hf_token:
